---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	draft(draft)
	critique(critique)
	revise(revise)
	__end__([<p>__end__</p>]):::last
	__start__ --> draft;
	critique --> revise;
	draft --> critique;
	revise --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
